services:
  app:
    build: .
    container_name: brazilian_stars_clean
    restart: unless-stopped
    ports:
      - "4101:4101"
    environment:
      - PORT=4101
      - DATABASE_URL=file:./data/database.db
      - JWT_SECRET=sua_chave_secreta_muito_forte_para_projeto_clean
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data:
